FROM node:10-alpine AS build
WORKDIR /app

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

COPY package*.json ./

RUN npm install
COPY . ./
RUN ./node_modules/.bin/tsc

# == Production
FROM ubuntu:18.04 AS production
WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive
ENV NODE_ENV=production
ENV PORT=3000
ENV CONNECTION_TIMEOUT=30000
ENV CHROME_PATH=/usr/bin/google-chrome

COPY sources.list /etc/apt/

# ---------
# MULTIVERSE
# ---------
RUN apt-get update && \
  apt-get install -y --no-install-recommends software-properties-common curl && \
  apt-add-repository multiverse && \
  apt-get update

# ---------
# MS CORE FONTS
# ---------
# from http://askubuntu.com/a/25614
RUN echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections &&\
  apt-get install -y --no-install-recommends fontconfig ttf-mscorefonts-installer
# ADD localfonts.conf /etc/fonts/local.conf

# Dependencies + NodeJS
RUN apt-get update && \
  apt-get install -y \
  # echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | debconf-set-selections && \
  # apt-get install -y software-properties-common &&\
  #apt-add-repository ppa:malteworld/ppa && apt-get update && apt-get install -y \
  # msttcorefonts \
  fonts-noto-color-emoji \
  fonts-noto-cjk \
  fonts-liberation \
  fonts-thai-tlwg \
  fontconfig \
  libappindicator3-1 \
  # pdftk \
  unzip \
  locales \
  gconf-service \
  libasound2 \
  libatk1.0-0 \
  libc6 \
  libcairo2 \
  libcups2 \
  libdbus-1-3 \
  libexpat1 \
  libfontconfig1 \
  libgcc1 \
  libgconf-2-4 \
  libgdk-pixbuf2.0-0 \
  libglib2.0-0 \
  libgtk-3-0 \
  libnspr4 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libstdc++6 \
  libx11-6 \
  libx11-xcb1 \
  libxcb1 \
  libxcomposite1 \
  libxcursor1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxi6 \
  libxrandr2 \
  libxrender1 \
  libxss1 \
  libxtst6 \
  ca-certificates \
  libappindicator1 \
  libnss3 \
  lsb-release \
  xdg-utils \
  wget && \
  fc-cache -f -v

# Install Node
RUN curl -L https://deb.nodesource.com/setup_10.x | sudo -E bash - &&\
  apt-get install --yes nodejs &&\
  apt-get install --yes build-essential

# It's a good idea to use dumb-init to help prevent zombie chrome processes.
ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
RUN chmod +x /usr/local/bin/dumb-init

COPY package*.json ./
COPY --from=build /app/dist ./dist

RUN npm install --production

# Cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 3000
ENTRYPOINT ["dumb-init", "--"]
CMD [ "node", "./dist/index.js" ]
